### PR TITLE
RN@0.29 application template

### PR DESCRIPTION
**Pull request by AlimovSV**

### CODE REVIEW

**Comment by WhatAKitty** [comment]
@AlimovSV  not working for RN0.29+?

**Comment by AlimovSV** [comment]
@WhatAKitty - with new android app [template](https://github.com/facebook/react-native/releases/tag/v0.29.0).

**Comment by WhatAKitty** [comment]
@AlimovSV  This change is backward compatible. And it will be works fine for RN0.29-?

**Comment by WhatAKitty** [comment]
@AlimovSV I will published a new version which is BREAKING CHANG.

**Comment by WhatAKitty** [comment]
no close.

**Pull request merged**
